---
title: "Quiz 2 Info"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

- **Quiz 2** will open on Wednesday at 3pm 

- The quiz will be administered over Sakai 

- The quiz has a total of 8 questions, with 5 multiple choice and 3 free response questions

- Concepts and interpretations from Lessons 6-9 will be tested
  - Think GLM tests in simple logistic regression, in multivariable regression, for a single variable, for groups of variables, and for interactions
    - How many coefficients are you testing?
    - Which test is appropriate for different scenarios?
  - Can you interpret an odds ratio in a simple logistic regression model AND a multivariable model?
  - Can you interpret a predicted probability?

- If you go to the "Tests & Quizzes" there is a Test Run for you to get familiar with the Sakai formatting.

- Quiz  instructions:
  - I have written a 30-minute quiz, but there is no time limit on the quiz. You will have from
  - Wednesday at 3pm to Sunday at 11pm to finish the quiz.
  - The quiz is open book and open notes. You may use books other than the class textbook, you may use anything on our course webpage, and you may use reference websites (like Wikipedia, Googling expected value of specific distribution, etc.).
  - No cheating will be tolerated. Cheating includes:
  - Using ChatGPT
  - Copy and pasting the question from Sakai to any search engine. 
  - Using question and answer threads typically seen on sites like StackExchange, WikiHow, Quora, Reddit, StackOverflow, Chegg, etc.    
  - Asking other students, sharing quiz work or sharing quiz results. 
  - Each question is worth 3 points, including multiple choice and free response questions.


