---
title: "Schedule"
date: "today"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

```{css, echo=FALSE}
.title{
  font-size: 30px;
  color: #5B9BD5;
  background-color: #fff;
  padding: 0px;
}

.monday-wednesdays table tbody tr:nth-child(n+1):nth-child(-n+4) td, 
.monday-wednesdays table tbody tr:nth-child(n+13):nth-child(-n+16) td,
.monday-wednesdays table tbody tr:nth-child(n+25):nth-child(-n+27) td,
.monday-wednesdays table tbody tr:nth-child(n+34):nth-child(-n+36) td,
.monday-wednesdays table tbody tr:nth-child(n+45):nth-child(-n+47) td,
.monday-wednesdays table tbody tr:nth-child(56) td{
  background-color: #F2F2F2 !important;
  color: black; 
}



.assignments table tbody tr:nth-child(11) td, 
.assignments table tbody tr:nth-child(17) td,
.assignments table tbody tr:nth-child(n+21):nth-child(-n+23) td,
.assignments table tbody tr:nth-child(28) td,
.assignments table tbody tr:nth-child(32) td,
.assignments table tbody tr:nth-child(n+37):nth-child(-n+39) td, 
.assignments table tbody tr:nth-child(43) td, 
.assignments table tbody tr:nth-child(n+48):nth-child(-n+50) td, 
.assignments table tbody tr:nth-child(n+57):nth-child(-n+58) td{
  background-color: #f0f6fc !important;
  color: #5B9BD5; 
}

.red table tbody tr:nth-child(5) td,
.red table tbody tr:nth-child(12) td,
.red table tbody tr:nth-child(18) td,
.red table tbody tr:nth-child(24) td,
.red table tbody tr:nth-child(29) td,
.red table tbody tr:nth-child(33) td,
.red table tbody tr:nth-child(40) td,
.red table tbody tr:nth-child(44) td,
.red table tbody tr:nth-child(51) td,
.red table tbody tr:nth-child(55) td {
  background-color: #C2352F !important; /* A light red; use 'red' for bright red */
  height: 5px; 
}
```

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

::::: assignments
:::: monday-wednesdays
::: red
| Week | Date | Key Info | Exit tix | Echo 360 | Les-son | Topic | Slides HTML | Slides PDF | Slides Notes | Muddy Points |
|:--:|:--:|:--:|:--:|:--:|:--:|:---|:--:|:--:|:--:|:--:|
| 1 | `{r} w1d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/01_Intro/01_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUN1pQMEs0Mk00MVpYRzJUNkpMT0NKVkc1UiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-03-30T13:00:00.000_2026-03-30T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 1 | Welcome | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/01_Intro/01_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/01_Intro/01_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/01_Intro/01_Intro_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  | 2 | Introduction to Categorical Analysis | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/02_Intro_CDA/02_Intro_CDA.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/02_Intro_CDA/02_Intro_CDA.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/02_Intro_CDA/02_Intro_CDA_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/02_Intro_CDA/02_Intro_CDA_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w1d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMjFZTFZaUUZCT0FFQzlOQ1JLRVBNVUQxMyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-01T13:00:00.000_2026-04-01T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 2 | Introduction to Categorical Analysis, continued | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/02_Intro_CDA/02_Intro_CDA.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/02_Intro_CDA/02_Intro_CDA.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/02_Intro_CDA/02_Intro_CDA_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/02_Intro_CDA/02_Intro_CDA_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  | 3 | Measurement of Association for Contingency Tables | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURVBBTjU0WDk0NUNRVVYyVVpESVRCTjc3SCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-06T13:00:00.000_2026-04-06T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 3 | Measurement of Association for Contingency Tables, continued | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  | 4 | Measurements of Association and Agreement | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  | PE Presentation with Jamie | [[{{< iconify ri slideshow-fill size=30px >}}](https://ohsuitg.sharepoint.com/:p:/r/sites/PH.SPH-Academic-Affairs/Practice%20Experience%20%20Integrative%20Project/PE.IP%20Admin/PE.IP%20Events.Presentations/Classroom%20Visits/2026.03%20PE%20Spring%20Class%20Visits.pptx?d=w132b016e414241bf8a35ce6383efc8c5&csf=1&web=1&e=hyIfs9)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/04_Meas_Assoc_Agree/2026.03%20PE%20Spring%20Class%20Visits.pdf)]{style="color:#f8f5f0;"} |  |  |
|  | `{r} w2d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNkFPVERJNEhONzhaQ1NCMEZENlJMOFNRTSQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-08T13:00:00.000_2026-04-08T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 4 | Measurements of Association and Agreement, continued | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  | 5 | Simple Logistic Regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | **`r lab1 %>% format("%m/%d")`** |  |  |  |  | **Lab 1 due \@ 11 pm** |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 3 | `{r} w3d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMU04WFBBRUNHTUxWWkk2OElFTEZZQVpBQiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-13T13:00:00.000_2026-04-13T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 5 | Simple Logistic Regression, continued | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  | 6 | Interpretations and Visualizations of Odds Ratios | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w3d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/L01_Discussion/L01_Discussion_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ0hFMTJCRE5XUzJCQ1dMVUhUVElOUFRLOCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-15T13:00:00.000_2026-04-15T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 6 | Interpretations and Visualizations of Odds Ratios, continued | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  | **Required in-person attendance:** Lab 1 Discussion | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/L01_Discussion/L01_Discussion.qmd)]{style="color:#f8f5f0;"} |  |  | [[{{< iconify pajamas question size=30px >}}](/lessons/L01_Discussion/L01_Discussion_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw1 %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**HW 1 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 4 | `{r} w4d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/07_Pred_Viz/07_Pred_Viz_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUME1VVFNDUDA4SERWU0YySDRMR0xaM1JaNiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-20T13:00:00.000_2026-04-20T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 7 | Predictions and Visualizations in Simple Logistic Regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/07_Pred_Viz/07_Pred_Viz.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/07_Pred_Viz/07_Pred_Viz.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/07_Pred_Viz/07_Pred_Viz_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/07_Pred_Viz/07_Pred_Viz_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w4d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOFVDRkVGMkpNOEFQQVpUTFZOWVlQS1EwUSQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-22T13:00:00.000_2026-04-22T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 8 | Tests for GLMs using Likelihood function | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r q1_open %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Quiz 1 opens at 3pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  | [**`r lab2 %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Lab 2 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  | [**`r q1_close %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Quiz 1 closes at 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 5 | `{r} w5d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOFVPTFBKV01JTE9LOUU4Q1JUOVlJUkZDTyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-27T13:00:00.000_2026-04-27T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 9 | Multiple Logistic Regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w5d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/10_Interactions/10_Interactions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURUNSNUgzWEVCMVVIM1FSS1NXTzhOMExZUCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-04-29T13:00:00.000_2026-04-29T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 10 | Interactions | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/10_Interactions/10_Interactions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/10_Interactions/10_Interactions.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  | **Required in-person attendance:** Lab 2 Discussion | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/L02_Discussion/L02_Discussion.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/L02_Discussion/L02_Discussion.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw2 %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**HW 2 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 6 | `{r} w6d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-05-04T13:00:00.000_2026-05-04T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 10 | Interactions, continued | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/10_Interactions/10_Interactions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/10_Interactions/10_Interactions.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w6d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_889be0dd-4e06-4af6-a433-6d3fa3cd68b5_87bbad0a-58f2-4758-a290-b95378fbbab4_2026-05-06T13:00:00.000_2026-05-06T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | 12 | Assessing Model Fit | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/12_Assessing_fit/12_Assessing_fit.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/12_Assessing_fit/12_Assessing_fit.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r lab3 %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Lab 3 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 7 | `{r} w7d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 13 | Model Diagnostics | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/13_Model_diagnostics/13_Model_diagnostics.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/13_Model_diagnostics/13_Model_diagnostics.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  | **Required in-person attendance:** Lab 3 Discussion | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/L03_Discussion/L03_Discussion.qmd)]{style="color:#f8f5f0;"} |  |  |  |
|  | `{r} w7d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 14 | Model Building | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/14_Model_building/14_Model_Building.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/14_Model_building/14_Model_Building.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q2_open %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Quiz 2 opens at 3pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  | [**`r hw3 %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**HW 3 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  | [**`r q2_close %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Quiz 2 closes at 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 8 | `{r} w8d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 11 | Numerical Problems | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/11_Numeric_Problems/11_Numeric_problems.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/11_Numeric_Problems/11_Numeric_problems.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w8d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 15 | Other types of categorical regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/15_Other_regression/15_Other_regression.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/15_Other_regression/15_Other_regression.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r lab4 %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Lab 4 due 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 9 | `{r} w9d1 %>% format("%m/%d")` |  |  |  |  | No class, Memorial Day |  |  |  |  |
|  | `{r} w9d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 16 | Log-binomial regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/16_Log_binom_reg/16_Log_binom_reg.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/16_Log_binom_reg/16_Log_binom_reg.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  | **Required in-person attendance:** Lab 4 Discussion |  |  |  |  |
|  | [**`r q3_open %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Quiz 3 opens at 3pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  | [**`r hw4 %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**HW 4 due 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  | [**`r q3_close %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Quiz 3 closes at 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 10 | `{r} w10d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 17 | Missing Data | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/17_Missing_data/17_Missing_data.pptx) [{{< iconify clarity group-solid size=29px >}}](/lessons/17_Missing_data/17_Activity_dogs.pptx)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/17_Missing_data/17_Missing_data.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w10d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 18 | Poisson regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/18_Poisson_regression/18_Poisson_regression.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/18_Poisson_regression/18_Poisson_regression.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  |  |  | 19 | Project Poster Guidelines | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/19_Poster_help/19_Poster_help.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/19_Poster_help/19_Poster_help.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  |  |  |  |  |  |
| 11 | `{r} w11d1 %>% format("%m/%d")` |  |  |  |  | **Required in-person attendance:** Project Day!! |  |  |  |  |
|  | [**`r proj %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**Project due 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |
|  | [**`r last_day %>% format("%m/%d")`**]{style="color:#5B9BD5;"} |  |  |  |  | [**All late coursework due 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |
:::
::::
:::::
