---
title: "Lab 4"
author: "Your name here!!!"
subtitle: "BSTA 513/613"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    self-contained: true
    embed-resources: true
    number-sections: true
    number-depth: 4
editor_options: 
  chunk_output_type: console
execute:
  freeze: auto  # re-render only when source changes
---

```{r}
#| message: false
#| warning: false
#| echo: false

# PLEASE DO NOT REMOVE THIS CODE CHUNK!!!
### ADD YOUR LIBRARIES HERE!!! ####

library(tidyverse)
library(gtsummary)
library(here)
```

## Directions

This is your **editing** file. **Please do not remove anything from this editing file!!** You will only add your code and work to this file.

## Lab activities

::: callout-note
I have left it up to you to load the needed packages for this lab.
:::

### Restate project type

::: callout-important
#### Task

Restate your project type: LASSO or purposeful model selection.

**Purposeful model selection only:** Please restate your research question below using the provided format (1 sentence). You can change the wording if you'd like, but please make sure it is still clear. It’s repetitive, but it helps me contextualize my feedback as I look through your lab.
:::

**Project type:** LASSO or purposeful model selection

**Purposeful model selection only:** In this study, we will investigate the association between food insecurity and \_\_\_\_\_\_\_\_.


### Build your model

::: callout-important
#### Task

Build a model for your outcome:

1.  Use LASSO to build a model with no interactions
2.  Use Purposeful model selection to build a model with at least one interaction
:::

### Assess your model fit

::: callout-important
#### Task
Calculate the ROC-AUC of your model.
:::

### Perform model diagnostics

::: callout-important
#### Task
Check your diagnostic plots and cutoffs (change in Pearson residuals, change in coefficients, and leverage) to identify and investigate any influential or outlier observations. Are these observations feasible?
:::

### OPTIONAL: Interpret your results

::: callout-important
#### OPTIONAL Task
OPTIONAL: Update your visualizations and interpretations from Lab 3 based on your final model.
:::
