---
title: "Lab 2"
author: "Your name here!!!"
subtitle: "BSTA 513/613"
description: "Due: May 2, 2024 at 11pm"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
    self-contained: true
    embed-resources: true
    number-sections: true
    number-depth: 4
editor_options: 
  chunk_output_type: console
execute:
  freeze: auto  # re-render only when source changes
---

```{r}
#| message: false
#| echo: false

# PLEASE DO NOT REMOVE THIS CODE CHUNK!!!
### ADD YOUR LIBRARIES HERE!!! ####

library(tidyverse)
library(gtsummary)
library(here)
```

::: callout-caution
This lab is NOT ready to be worked on!! (3/30/2026)
:::

## Lab activities

::: callout-note
I have left it up to you to load the needed packages for this lab.
:::

### Restate project type

::: callout-important
#### Task

Restate your project type: LASSO or purposeful model selection.

**Purposeful model selection only:** Please restate your research question below using the provided format (1 sentence). You can change the wording if you'd like, but please make sure it is still clear. It’s repetitive, but it helps me contextualize my feedback as I look through your lab.
:::

**Project type:** LASSO or purposeful model selection

**Purposeful model selection only:** In this study, we will investigate the association between food insecurity and \_\_\_\_\_\_\_\_.

### Make sure variables are coded correctly

::: callout-important
#### Task

-   Use `class()` to determine the class of the variables you selected from Lab 1 (including the outcome).
-   Change the variable type to the appropriate type.
:::

### For purposeful model selection only

::: callout-important
#### Task

Redo your Table 1 with correct variable types and showing Yes/No categories.
:::

### Consider potential confounders and effect modifiers

#### For purposeful model selection only

::: callout-important
#### Task

Fill in the below table (or any other way you wish to present the same information).
:::

| Variable name | Confounder, Effect modifier, or nothing? | Reasoning (1-2 sentences) |
|-------------------|---------------------------|---------------------------|
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |

#### For LASSO only

::: callout-important
#### Task

Fill in the below table (or any other way you wish to present the same information).
:::

| Rank | Variable name | Reasoning (1-2 sentences) |
|------|---------------|---------------------------|
| 1    |               |                           |
| 2    |               |                           |
| 3    |               |                           |
| 4    |               |                           |
| 5    |               |                           |
| 6    |               |                           |
| 7    |               |                           |
| 8    |               |                           |
| 9    |               |                           |
| 10   |               |                           |

### Bivariate exploratory data analysis

#### Categorical predictors: Create contingency tables

::: callout-important
#### Task

-   Create contingency tables for all categorical covariates with food insecurity. 
-   Take note of any cell counts that are less than 10
:::

#### Bivariate exploratory data analysis

::: callout-important
#### Task

-   Use `ggpairs()` to quickly look at the relationship between numeric variables and food insecurity.
-   Think back to your Intro to Biostats course. **How could you test the difference in the distribution of a numeric variable between food insecurity groups?**
:::

### Fit simple logistic regression

::: callout-important
#### Task

-   Using `glm()`, run a logistic regression with food insecurity and your main variable of interest. (For LASSO: pick one variable that you think will be an important predictor)
-   Display the unadjusted odds ratio(s) of the regression. You can use `tidy()` or `logistic.display()`
-   Interpret the unadjusted odds ratio(s) (with 95% confidence interval). If you're main variable is multi-level and has more than 5 categories, then you can limit your interpretations to 5 odds ratios.
:::

### Plot the predicted probability

::: callout-important
#### Task

Plot or make a table of your predicted probabilities.
:::
